name: publish
description: Publish to PyPi or Test PyPi

inputs:
  pypi_token:
    description: API Token to push to the main PyPi repository
    required: true

  pypi_test_token:
    description: API Token to push to the test PyPi repository
    required: true

runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #            publish to pypi test
    #----------------------------------------------
    - name: Publish to PyPi Test
      if: github.ref != 'refs/heads/main'
      shell: bash
      env:
        POETRY_PYPI_TOKEN_PYPI_TEST: ${{ inputs.pypi_test_token }}
      run: |
        cat pyproject.toml | grep "version = "
        poetry config repositories.pypi_test https://test.pypi.org/legacy/
        poetry publish -r pypi_test
    #----------------------------------------------
    #               publish to pypi
    #----------------------------------------------
    - name: Publish to PyPi
      if: github.ref == 'refs/heads/main'
      shell: bash
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ inputs.pypi_token }}
      run: |
        cat pyproject.toml | grep "version = "
        poetry publish --build
