name: publish
description: Publish to PyPi or Test PyPi

inputs:
  pypi_token:
    description: API Token to push to the main PyPi repository
    required: true

  pypi_test_token:
    description: API Token to push to the test PyPi repository
    required: true

runs:
  using: "composite"
  steps:
    - name: Print build version
      shell: bash
      run: cat pyproject.toml | grep "^version = "
    #----------------------------------------------
    #            publish to pypi test
    #----------------------------------------------
    - name: Publish to PyPi Test
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        poetry config repositories.pypi_test https://test.pypi.org/legacy/
        poetry config pypi-token.pypi_test ${{ inputs.pypi_test_token }}
        poetry publish -r pypi_test --build
    #----------------------------------------------
    #               publish to pypi
    #----------------------------------------------
    - name: Publish to PyPi
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        poetry config pypi-token.pypi ${{ inputs.pypi_token }}
        poetry publish --build
