name: publish
description: Publish to PyPi or Test PyPi

runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #            publish to pypi test
    #----------------------------------------------
    - name: Publish to PyPi Test
      if: github.ref != 'refs/heads/main'
      shell: bash
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.POETRY_PYPI_TOKEN_PYPI_TEST }}
        poetry publish -r testpypi
    #----------------------------------------------
    #               publish to pypi
    #----------------------------------------------
    - name: Publish to PyPi
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        poetry config pypi-token.pypi ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        poetry publish
