name: semantic-release
runs:
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        if [ ! -e package-lock.json ]; then
          npm i
          fi
        npm ci
        npm install @semantic-release/git @semantic-release/changelog @google/semantic-release-replace-plugin -D

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
