# ---------------------------------------------------------------
# build and test make use of:
# https://github.com/marketplace/actions/install-poetry-action
#
# upload code coverage makes use of:
# https://github.com/marketplace/actions/pytest-coverage-comment

name: test

runs:
  steps:
    #----------------------------------------------
    #    run test suite and output coverage file
    #----------------------------------------------
    - name: Test with pytest
      run: poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src --cov-report=xml tests/ | tee pytest-coverage.txt
    #----------------------------------------------
    #             upload coverage stats
    #----------------------------------------------
    - name: Pytest coverage comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
