name: dbr-cli-config
description: Configure Databricks CLI

runs:
  using: "composite"
  steps:
    - name: Delete .databrickscfg
      shell: bash
      run: |
        CONFIG_FILE="$HOME/.datatabrickscfg"

        if [ -f "$CONFIG_FILE" ]; then
            rm -f $CONFIG_FILE
            echo ".datatabrickscfg file has been deleted."
        else
            echo ".datatabrickscfg file does not exist."
        fi
